dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash
  - touch ~/.ssh/appuser ~/.ssh/appuser.pub
  # versions
  - PACKER_V=1.3.2
  - TERRAFORM_V=0.11.10
  - TFLINT_V=0.7.2
  - ANSIBLE_V=2.7.1
  - ANSIBLE_LINT_V=3.4.20
  # rename all .example files
  - echo "Files to be renamed:" && for i in $(find `pwd` -name "*.example");  do echo "$i" ; done
  - for i in $(find `pwd` -name "*.example");  do mv "$i" "${i%.example}"; done && echo "Done"
install:
  # packer
  - wget -P /tmp/ https://releases.hashicorp.com/packer/${PACKER_V}/packer_${PACKER_V}_linux_amd64.zip
  - sudo unzip -o /tmp/packer_${PACKER_V}_linux_amd64.zip -d /usr/local/bin/
  - packer --version
  # terraform
  - wget -P /tmp/ https://releases.hashicorp.com/terraform/${TERRAFORM_V}/terraform_${TERRAFORM_V}_linux_amd64.zip
  - sudo unzip -o /tmp/terraform_${TERRAFORM_V}_linux_amd64.zip -d /usr/local/bin/
  - terraform --version
  # tflint
  - wget -P /tmp/ https://github.com/wata727/tflint/releases/download/v${TFLINT_V}/tflint_linux_amd64.zip
  - sudo unzip /tmp/tflint_linux_amd64.zip -d /usr/local/bin/
  - tflint -v
  # ansible
  - sudo pip install ansible==${ANSIBLE_V}
  - ansible --version
  # ansible-lint
  - sudo pip2 install ansible-lint==${ANSIBLE_LINT_V}
  - ansible-lint --version

script:
  # packer validation
  - cd ${TRAVIS_BUILD_DIR}
  - packer validate -var-file=packer/app-vars.json packer/app.json
  - packer validate -var-file=packer/db-vars.json packer/db.json
  - cd ${TRAVIS_BUILD_DIR}/packer
  - packer validate -var-file=variables.json ubuntu16.json
  # terraform validation
  - cd ${TRAVIS_BUILD_DIR}/terraform
  - terraform init -backend=false
  - terraform validate && tflint --ignore-module=SweetOps/storage-bucket/google
  - cd ${TRAVIS_BUILD_DIR}/terraform/stage
  - terraform init -backend=false
  - terraform validate && tflint
  - cd ${TRAVIS_BUILD_DIR}/terraform/prod
  - terraform init -backend=false
  - terraform validate && tflint
  # ansible lint
  - cd ${TRAVIS_BUILD_DIR}/ansible
  - ansible-lint --exclude=playbooks/clone.yml --exclude=roles/jdauphant.nginx playbooks/*

notifications:
  slack:
    rooms:
      secure: ZnoJAvFUMuvn7T50amKO2EWISzmh0CjZU9wV67Yts1+gZXmjq3tPSP00fyZ9ZAKFCt9C4K1nqUbHI/VkoUM9SUOggD9+K8dhYtNtOrFiMEwuqSQVymOuime28u1goFtd8H/mMxOCUXNUZsPzHv2yHUyAigHzIDOzp2vBBQxPuIMN7j1x0HIyPeeS/b6Sd/6+uoCJDOZ7ZDDRi/yKplplKenIuzpUR1uMI8MQ+Sp9a2mlZBsm/AliXxjjVwbBWrStw9cvbs+fRQzJITMtRzmFHYVYeBQefm019I7KXB9EHQzwr/T4Fp8vlo9/xHIrHaX7v5JdvS6kUn4f+uoI2YmL++X+axf6SyrBdEvQQVNiH5kW16KpHyl7qu9hKTye6pdzKUXJ6FxKfyaRT9ooKmntr5I7J1ulBu+SXM/vRrIb2kUnxY4kCJKPy6kdNUD/Oz57d0pJt8chHEzXy7tTGOT84Zu6U4QwqSqtBvVrlgxiZ0bSkBX9afuHLZcY2Fs9deiNJp82wN9OXsFOihjjjhZWrvt+hk07z9jdVuplN5N1/uCPC0Bc4L3FZrJgixVjJVpyvviq6YUqTa+RxxRDHJ2t/MUUzuR93P9mYCp8yCRSwbE2vFP6orf5/I+vLVInY3zJNOhT6hXzIHDTkem0+UXPunpckKcSWM76/CZMRPRYas8=
