---
- name: Install apt key
  apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com
  tags: install

- name: Add repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    update_cache: yes
  tags: install

- name: Install MongoDB
  apt:
    name: mongodb-org
  tags: install

- name: Run and enable mongod service
  systemd:
    name: mongod
    state: started
    enabled: yes
  tags: install
