---
- name: Update cache and install ruby and bundle
  hosts: all
  become: true
  tasks:
    - name: Apt update
      apt:
        update_cache: yes
        name:
          - ruby-full
          - ruby-bundler
          - build-essential
